# Imports

In [1]:
import numpy as np
import pandas as pd

# Load Data

In [4]:
df = pd.read_csv("archive/diabetes_binary_health_indicators_BRFSS2015.csv")
df

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [5]:
df_modded = df.copy()

### Let's one hot encode the column (We do this for every column moving forward)

In [10]:
df_modded["Underweight"] = np.where(df["BMI"] < 18.5, 1, 0)
df_modded["Healthy Weight"] = np.where((df["BMI"] >= 18.5) & (df["BMI"] < 25), 1, 0)
df_modded["Overweight"] = np.where((df["BMI"] >= 25) & (df["BMI"] < 30), 1, 0)
df_modded["Class 1 Obesity"] = np.where((df["BMI"] >= 30) & (df["BMI"] < 35), 1, 0)
df_modded["Class 2 Obesity"] = np.where((df["BMI"] >= 35) & (df["BMI"] < 40), 1, 0)
df_modded["Class 3 Obesity"] = np.where(df["BMI"] >= 40, 1, 0)

In [11]:
df_modded = df_modded.drop('BMI',axis=1)

In [12]:
df_modded = pd.get_dummies(df_modded,columns=['GenHlth'],dtype=int)

In [13]:
df_modded = df_modded.rename(columns={'GenHlth_1.0': 'Excellent General Health', 'GenHlth_2.0': 'Very Good General Health', 'GenHlth_3.0': 'Good General Health', 'GenHlth_4.0': 'Fair General Health', 'GenHlth_5.0': 'Poor General Health'})

In [14]:
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,Healthy Weight,Overweight,Class 1 Obesity,Class 2 Obesity,Class 3 Obesity,Excellent General Health,Very Good General Health,Good General Health,Fair General Health,Poor General Health
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,1,0,0,0,0,1
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,0,0,1,0,0
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,0,0,0,0,0,0,0,1
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,1,0,0,0,0,1,0,0,0
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,1,0,0,1,0,0
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,0
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,1,0,0,0,1,0,0,0,0
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,0,0,0,0,0,0,1,0,0
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,1,0,0,0,0,1,0,0,0

In [15]:
df_modded["Mentally Healthy"] = np.where(df["MentHlth"] == 0, 1, 0)

In [16]:
df_modded = df_modded.drop('MentHlth',axis=1)
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,Overweight,Class 1 Obesity,Class 2 Obesity,Class 3 Obesity,Excellent General Health,Very Good General Health,Good General Health,Fair General Health,Poor General Health,Mentally Healthy
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,1,0,0,0,0,1,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0,0,0,0,1,0,0,1
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,0,0,0,0,0,0,0,1,0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1,0,0,0,0,1,0,0,0,1
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,1,0,0,1,0,0,1
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,1
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1,0,0,0,1,0,0,0,0,1
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,1,0,0,1
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1,0,0,0,0,1,0,0,0,1

In [17]:
df_modded["Physically Healthy"] = np.where(df["PhysHlth"] == 0, 1, 0)

In [18]:
df_modded = df_modded.drop('PhysHlth',axis=1)

In [19]:
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,Class 1 Obesity,Class 2 Obesity,Class 3 Obesity,Excellent General Health,Very Good General Health,Good General Health,Fair General Health,Poor General Health,Mentally Healthy,Physically Healthy
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,1,0,0,0,0,1,0,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,1,0,0,1,1
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,1,0,0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,1,0,0,0,1,1
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,1,0,0,1,0,0,1,0
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,1,0,1,1
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,0,0,1,0,0,0,0,1,1
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,1,0,0,1,1
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,0,0,0,1,0,0,0,1,1

In [20]:
df_modded = pd.get_dummies(df_modded,columns=['Age'],dtype=int)

In [21]:
df_modded = df_modded.rename(columns={'Age_1.0': 'Age 18 to 24', 'Age_2.0': 'Age 25 to 29', 'Age_3.0': 'Age 30 to 34', 'Age_4.0': 'Age 35 to 39', 'Age_5.0': 'Age 40 to 44'
                                      , 'Age_6.0': 'Age 45 to 49', 'Age_7.0': 'Age 50 to 54', 'Age_8.0': 'Age 55 to 59', 'Age_9.0': 'Age 60 to 64'
                                      , 'Age_10.0': 'Age 65 to 69', 'Age_11.0': 'Age 70 to 74', 'Age_12.0': 'Age 75 to 79', 'Age_13.0':'Age 80 or older'})

In [22]:
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,Age 35 to 39,Age 40 to 44,Age 45 to 49,Age 50 to 54,Age 55 to 59,Age 60 to 64,Age 65 to 69,Age 70 to 74,Age 75 to 79,Age 80 or older
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,1,0,0,0,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,1,0,0,0,0,0,0
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,1,0,0,0,0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,1,0,0
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,1,0,0,0,0,0,0,0,0
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,0
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,1,0,0,0,0,0,0
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,0,0,0,0,1,0,0,0,0

In [23]:
df_modded["Never Attended or Only Kindergarten"] = np.where(df["Education"] == 1, 1, 0)
df_modded["Grades 1 through 8 (Elementary)"] = np.where(df["Education"] == 2, 1, 0)
df_modded["Grades 9 through 11 (Some high school)"] = np.where(df["Education"] == 3, 1, 0)
df_modded["Grade 12 or GED (High school graduate)"] = np.where(df["Education"] == 4, 1, 0)
df_modded["College 1 year to 3 years (Some college or technical school)"] = np.where(df["Education"] == 5, 1, 0)
df_modded["College 4 years or more (College graduate)"] = np.where(df["Education"] == 6, 1, 0)

In [24]:
df_modded = df_modded.drop('Education',axis=1)

In [25]:
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,Age 65 to 69,Age 70 to 74,Age 75 to 79,Age 80 or older,Never Attended or Only Kindergarten,Grades 1 through 8 (Elementary),Grades 9 through 11 (Some high school),Grade 12 or GED (High school graduate),College 1 year to 3 years (Some college or technical school),College 4 years or more (College graduate)
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,1,0,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,1,0,0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,1,0,0,0,0,1,0,0,0
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,1
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,1,0,0,0,0
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,0,1,0
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,0,0,0,0,0,1,0
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [26]:
df_modded = pd.get_dummies(df_modded,columns=['Income'],dtype=int)

In [27]:
df_modded = df_modded.rename(columns={'Income_1.0': 'Earns Less than $10,000 Annually', 'Income_2.0': 'Earns $10,000-$14,999 Annually', 'Income_3.0': 'Earns $15,000-$19,999 Annually', 'Income_4.0': 'Earns $20,000-$24,999 Annually', 'Income_5.0': 'Earns $25,000-$34,999 Annually'
                                      , 'Income_6.0': 'Earns $35,000-$49,999 Annually', 'Income_7.0': 'Earns $50,000-$74,999 Annually', 'Income_8.0': 'Earns More than $75,000 Annually'})

In [28]:
df_modded

,Diabetes_binary,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,College 1 year to 3 years (Some college or technical school),College 4 years or more (College graduate),"Earns Less than $10,000 Annually","Earns $10,000-$14,999 Annually","Earns $15,000-$19,999 Annually","Earns $20,000-$24,999 Annually","Earns $25,000-$34,999 Annually","Earns $35,000-$49,999 Annually","Earns $50,000-$74,999 Annually","Earns More than $75,000 Annually"
0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,1,0,0,0,0,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0,1,1,0,0,0,0,0,0,0
2,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,1
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,1,0,0
4,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,1,0,0,0,0,0,0,1,0
253676,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
253677,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1,0,0,1,0,0,0,0,0,0
253678,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,0,1,0,0,0,0,0,0,0
253679,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,1,0,1,0,0,0,0,0,0

In [30]:
df_modded.to_csv('Phase 2 data.csv', index= False)

In [2]:
df = pd.read_csv('Phase 2 data.csv')
y = df['Diabetes_binary']
X = df.drop(['Diabetes_binary'],axis=1)

In [3]:
y

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
253675    0.0
253676    1.0
253677    0.0
253678    0.0
253679    1.0
Name: Diabetes_binary, Length: 253680, dtype: float64

In [4]:
X

,HighBP,HighChol,CholCheck,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,...,College 1 year to 3 years (Some college or technical school),College 4 years or more (College graduate),"Earns Less than $10,000 Annually","Earns $10,000-$14,999 Annually","Earns $15,000-$19,999 Annually","Earns $20,000-$24,999 Annually","Earns $25,000-$34,999 Annually","Earns $35,000-$49,999 Annually","Earns $50,000-$74,999 Annually","Earns More than $75,000 Annually"
0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,1,0,0,0,0,0
1,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,1,1,0,0,0,0,0,0,0
2,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
3,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,1,0,0
4,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,1,0,0,0,0,0,0,1,0
253676,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
253677,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1,0,0,1,0,0,0,0,0,0
253678,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,1,0,1,0,0,0,0,0,0,0
253679,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0,1,0,1,0,0,0,0,0,0